apiVersion: v1
kind: Service
metadata:
  name: dockerdemo-service
spec:
  selector:
    app: dockerdemo
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdemo
spec:
  selector:
    matchLabels:
      app: dockerdemo
  replicas: 1
  template:
    metadata:
      labels:
        app: dockerdemo
    spec:
      containers:
      - name: dockerdemo
        image: dockerdemo:v1
        ports:
        - containerPort: 5000